Update README.md
Unexpected error running initialize() for v2g_liberty because of missing wallbox_plus_car_roundtrip_efficiency declaration under v2g_liberty under apps.yaml 

--
KeyError: 'wallbox_plus_car_roundtrip_efficiency'
self.WALLBOX_PLUS_CAR_ROUNDTRIP_EFFICIENCY = float(self.args["wallbox_plus_car_roundtrip_efficiency"])
File "/config/appdaemon/apps/v2g-liberty/v2g_liberty.py", line 53, in initialize result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run response = future.result()
File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 337, in run_in_executor await utils.run_in_executor(self, init)
File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 165, in initialize_app